version: "3"
services: 
    selenium:
      container_name: selenium
      image: selenium/standalone-chrome
      ports:
        - 4444:4444
    vending-machine-tests:
      container_name: vending-machine-tests 
      image: vending-machine-tests:latest
      stdin_open: true
      volumes:
          - .:/build
    vending-machine-app:
      container_name: vending-machine-app
      image: vending-machine-app:latest
      stdin_open: true
      environment:
        FLASK_APP: /build/src/app
      ports:
        - 5000:5000
